### ISSUE TITLE
readme中的链接有问题，直接点击的话会把 `https://huggingface.co/RWKV）下载合适的模型` 当作一个链接

### ISSUE THREAD

**Issue by ssdreamC** [bilibini/Meow-AI#1]
readme中的链接有问题，直接点击的话会把 `https://huggingface.co/RWKV）下载合适的模型` 当作一个链接，markdown的链接格式如下
```
// [text](url)
根据自己电脑配置在模型网站（[https://huggingface.co/RWKV](https://huggingface.co/RWKV)）下载合适的模型  
```
效果：
// [text](url)
根据自己电脑配置在模型网站（[https://huggingface.co/RWKV](https://huggingface.co/RWKV)）下载合适的模型

**Comment by bilibini** [comment]
确实是这样，感谢提出的建议，已修改readme
